### ISSUE TITLE
TYPE_CHOICE on Android 6 not working

### ISSUE THREAD

**Issue by kreuli** [googlesamples/android-AppRestrictions#1]
Hi,

on my Android 6 device (Samsung Tab S2), the value for the TYPE_CHOICE RestrictionEntry does not show up in the restricted profile, 'getSelectedString' returns an empty string instead of the selected value. 
The other two types TYPE_BOOLEAN and TYPE_MULTI_SELECT work correctly.
The sample works successfully on my Android 4.4.2 device (LG Tab Pro).
Is this a known issue in Android 6?

Cheers,
Ulrich

**Comment by nielsnl68** [comment]
I have the same issue with Android 7.0.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
